name: Deploy to Azure 

on:
  workflow_dispatch:
   

jobs:
  deploy:
    name: Deploy to Azure
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2.2.0
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Azure CLI script
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            if ! az group show --name RG-Dev.Nis-EastUS &>/dev/null; then
              az group create --name RG-Dev.Nis-EastUS --location eastus
            fi
            if ! az group show --name RG-Dev.Nis-WestUS &>/dev/null; then
              az group create --name RG-Dev.Nis-WestUS --location westus
            fi
      - uses: azure/arm-deploy@v2
        with:
          resourceGroupName: RG-Dev.Nis-EastUS
          template: ./EastUS-Deployments.json
          
      - uses: azure/arm-deploy@v2
        with:
          resourceGroupName: RG-Dev.Nis-WestUS
          template: ./WestUS-Deployments.json
            